version: '3'

services:
  zookeeper:
    image: jplock/zookeeper

  telegraf:
    image: local/telegraf
    volumes:
      - ${PWD}/config/telegraf.conf:/etc/telegraf/telegraf.conf
    command: --remote-config=homebase:6565 --region=${REGION:-west}
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s

  homebase:
    image: local/homebase
    ports:
      - 8082:8080
    environment:
      SPRING_PROFILES_ACTIVE: debug,docker
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        # allow time for ignite hand-off
        delay: 60s

  influxdb:
    image: influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000