version: '3'

services:
  zookeeper:
    image: jplock/zookeeper
    volumes:
      - ${PWD}/config/zookeeper-java.env:/opt/zookeeper/conf/java.env

  cassandra:
    image: cassandra:3.0
    volumes:
      - cassandra:/var/lib/cassandra
      - ${PWD}/config/cassandra-jvm.options:/etc/cassandra/jvm.options
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s

  telegraf:
    image: local/telegraf
    volumes:
      - ${PWD}/config/telegraf.conf:/etc/telegraf/telegraf.conf
    command: --remote-config=homebase:6565 --region=${REGION:-west}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s

  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    ports:
      - 9092:9092

  homebase:
    image: local/homebase
    ports:
      - 8083:8080
    environment:
      SPRING_PROFILES_ACTIVE: debug,docker
      JAVA_TOOL_OPTIONS: -XX:+UseG1GC -Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m -XX:+DisableExplicitGC
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        # allow time for ignite hand-off
        delay: 60s

  influxdb:
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: grafana
    volumes:
      - postgres:/var/lib/postgresql

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/grafana

volumes:
  cassandra:
  postgres:
  influxdb:
