version: '3'

services:
#  homebase:
#    build: .
#    ports:
#      - 8080:8080
#      - 6565:6565
  influxdb:
    image: influxdb
    ports:
      - 8083:8083
      - 8086:8086
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000