version: '3'

services:
  cassandra:
    image: cassandra:3.0
    volumes:
      - ${PWD}/data/cassandra:/var/lib/cassandra
      - ${PWD}/config/cassandra-jvm.options:/etc/cassandra/jvm.options
    ports:
      - 9042:9042
    environment:
      CASSANDRA_SEEDS: cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s

  influxdb:
    image: influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
