version: '3'

services:
  zookeeper:
    image: jplock/zookeeper

  cassandra:
    image: cassandra:3.0
    volumes:
      - cassandra:/var/lib/cassandra
# for dev testing
#    volumes:
#      - ${PWD}/data/cassandra:/var/lib/cassandra
#    ports:
#      - 9042:9042
#    environment:
#      CASSANDRA_SEEDS: cassandra

  telegraf:
    image: local/telegraf
    volumes:
      - ${PWD}/config/telegraf.conf:/etc/telegraf/telegraf.conf
    command: --remote-config=homebase:6565 --region=${REGION:-west}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s

  homebase:
    image: local/homebase
    ports:
      - 8083:8080
    environment:
      SPRING_PROFILES_ACTIVE: debug,docker
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        # allow time for ignite hand-off
        delay: 60s

  influxdb:
    image: influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

volumes:
  cassandra: