---
telegraf:
  regions:
   - west
   - central
   - east
logging:
  level:
    org.apache.ignite.spi.discovery.tcp.ipfinder.zk.TcpDiscoveryZookeeperIpFinder: warn

---
spring:
  profiles: debug
logging.level:
  com.rackspace.mmi.telegrafhomebase: debug

---
spring:
  profiles: docker
ignite:
  zk-connection: zookeeper:2181
cassandra:
  contact-points:
    - cassandra:9042