---
telegraf:
  regions:
   - west
   - central
   - east
logging:
  level:
    org.apache.ignite.spi.discovery.tcp.ipfinder.zk.TcpDiscoveryZookeeperIpFinder: warn

---
spring.profiles: debug
logging.level:
  com.rackspace.telegrafhomebase: debug

---
spring.profiles: docker
spring:
  profiles:
    include:
     - CassandraCacheStore
ignite:
  zk-connection: zookeeper:2181
cassandra:
  contact-points:
    - cassandra:9042
